name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14, 16]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install client dependencies
        working-directory: ./client
        run: npm install

#      - name: Install server dependencies
#        working-directory: ./server
#        run: npm install

      - name: Run client tests
        working-directory: ./client 
        run: npm test

#      - name: Run server tests
#        working-directory: ./server
#        run: npm test
